import { CodeBlockWriter } from 'ts-morph'
import type { GeneratedImportSpec } from '../ast'
import type { ModuleScanContext, StandaloneConfigOptions } from '../extension'
import type { ModuleImports, ModuleRoots } from '../scanner'
import { createTranslatableFieldsExtension } from '../extensions/translatable-fields'

const roots: ModuleRoots = {
  appBase: '/tmp/app/src/modules/test_mod',
  pkgBase: '/tmp/packages/core/src/modules/test_mod',
}

const imps: ModuleImports = {
  appBase: '@app/modules/test_mod',
  pkgBase: '@open-mercato/core/modules/test_mod',
}

function createContext(
  moduleId: string,
  processStandaloneConfig: (options: StandaloneConfigOptions) => string | null,
): ModuleScanContext {
  return {
    moduleId,
    roots,
    imps,
    importIdRef: { value: 0 },
    sharedImports: [],
    resolveModuleFile: jest.fn(),
    resolveFirstModuleFile: jest.fn(),
    processStandaloneConfig,
    sanitizeGeneratedModuleSpecifier: (importPath) => importPath,
  }
}

function renderConfig(
  writeConfig: NonNullable<StandaloneConfigOptions['writeConfig']>,
  options: { importName: string; moduleId: string },
): string {
  const writer = new CodeBlockWriter({ useTabs: false })
  writeConfig(options)(writer)
  return writer.toString()
}

function createStandaloneConfigRunner() {
  return (options: StandaloneConfigOptions): string => {
    const importName = `${options.prefix}_${options.modId}_${options.importIdRef.value++}`
    const importSpec: GeneratedImportSpec = {
      namespaceImport: importName,
      moduleSpecifier: `./${options.modId}/translations`,
    }

    ;(options.standaloneImports as GeneratedImportSpec[]).push(importSpec)
    if (options.sharedImports) {
      ;(options.sharedImports as GeneratedImportSpec[]).push(importSpec)
    }

    if (options.standaloneEntries && options.writeConfig) {
      options.standaloneEntries.push(options.writeConfig({ importName, moduleId: options.modId }))
    }

    return importName
  }
}

describe('createTranslatableFieldsExtension', () => {
  it('registers translations.ts as a standalone namespace import with fallback lookup', () => {
    const extension = createTranslatableFieldsExtension()
    const processStandaloneConfig = jest.fn(() => 'TRANS_FIELDS_orders_0')

    extension.scanModule(createContext('orders', processStandaloneConfig))

    expect(extension.id).toBe('registry.translatable-fields')
    expect(extension.outputFiles).toEqual(['translations-fields.generated.ts'])
    expect(processStandaloneConfig).toHaveBeenCalledTimes(1)

    const options = processStandaloneConfig.mock.calls[0][0] as StandaloneConfigOptions

    expect(options.relativePath).toBe('translations.ts')
    expect(options.prefix).toBe('TRANS_FIELDS')
    expect(options.standaloneEntries).toEqual([])
    expect(options.writeConfig).toBeDefined()

    const rendered = renderConfig(options.writeConfig!, {
      importName: 'TRANS_FIELDS_orders_0',
      moduleId: 'orders',
    })

    expect(rendered).toContain('moduleId: "orders"')
    expect(rendered).toContain('fields:')
    expect(rendered).toContain('"default"')
    expect(rendered).toContain('"translatableFields"')
    expect(rendered).toContain('TRANS_FIELDS_orders_0')
    expect(rendered).toContain('Record<string, string[]>')
  })

  it('generates a flattened registration file with module entries and exports', () => {
    const extension = createTranslatableFieldsExtension()
    const processStandaloneConfig = createStandaloneConfigRunner()

    extension.scanModule(createContext('orders', processStandaloneConfig))
    extension.scanModule(createContext('products', processStandaloneConfig))

    const output = extension.generateOutput().get('translations-fields.generated.ts')

    expect(output).toBeDefined()
    expect(output).toContain('// AUTO-GENERATED by mercato generate registry')
    expect(output).toContain('registerTranslatableFields')
    expect(output).toContain('./orders/translations')
    expect(output).toContain('./products/translations')
    expect(output).toContain('moduleId: "orders"')
    expect(output).toContain('moduleId: "products"')
    expect(output).toContain('"default"')
    expect(output).toContain('"translatableFields"')
    expect(output).toContain('for (const entry of entries)')
    expect(output).toContain('for (const [key, value] of Object.entries(entry.fields))')
    expect(output).toContain('collected[key] = value')
    expect(output).toContain('registerTranslatableFields(allFields)')
    expect(output).toContain('export const translatableFieldEntries = entries')
    expect(output).toContain('allTranslatableFields = allFields')
    expect(output).toContain('allTranslatableEntityTypes = Object.keys(allFields)')
  })

  it('does not contribute additional module declaration fields', () => {
    const extension = createTranslatableFieldsExtension()

    expect(extension.getModuleDeclContribution?.('orders')).toBeNull()
  })
})
