export { configSchema, type HackonConfig, type Lane, type AutoReadyMode, LANES, GREEN_LANES } from './config/schema'
export { loadConfig, resolveConfigPaths, ConfigError } from './config/loader'
export { RegistryStore } from './registry/store'
export { formatTaskId, parseTaskId } from './registry/id'
export { type TaskRecord, type TaskRegistry, type TaskSource, type RiskZone, type DuplicateRisk, type SourceType, EMPTY_REGISTRY } from './registry/types'
export { exec, execOrThrow, type ShellResult } from './lib/shell'
export { resolveWorkspacePaths, worktreePath, type WorkspacePaths } from './lib/paths'
export { Logger, logger } from './lib/logger'
export type { GitHubAdapter, GitHubPR, GitHubReview, GitHubCheckStatus, GitHubComment, GitHubIssue } from './github/adapter'
export { readPRState, type PRState } from './github/state-reader'
export { formatComment, parseCommentRole, type AgentRole } from './github/comments'
export { deriveTaskState, deriveStateFromPRState, derivePortalStatus, deriveJudgeStatus, branchExists, type DerivedState, type DerivedTaskState, type PortalStatus, type JudgeStatus } from './state/derive'
export { type DiscoveryCandidate, type DiscoveryResult } from './discovery/types'
export { findSkippedTests, findTodoTests, findModulesWithoutTests, repoSignalsToCandidates } from './discovery/repo-signals'
export { runSpecCoverage, integrationGapsToCandidates, type SpecCoverageReport } from './discovery/integration-gaps'
export { fetchOpenIssues, issuesToCandidates } from './discovery/github-issues'
export { rankCandidates, deduplicateCandidates } from './discovery/rank'
export { qualifyCandidate, type QualificationResult } from './qualification/qualify'
export { checkDuplicates, type DuplicateCheckResult } from './qualification/duplicates'
export { checkLaneCapacity, checkAutoReady, type PolicyCheckResult } from './qualification/policy'
export { generateBranchName, slugify } from './worktree/branch'
export { createWorktree, removeWorktree, listWorktrees, worktreeExists } from './worktree/lifecycle'
export { getGateProfile, type GateProfile } from './gates/profiles'
export { getDiffStats, getChangedFiles, checkForbiddenPaths, type DiffStats } from './gates/diff-check'
export { runGates, type GateResult, type GateRunResult } from './gates/runner'
export { buildPRBody, createDraftPR, formatPRTitle, type PRBodyParams, type ReviewSummary } from './github/pr'
export { generateImplementerPrompt } from './prompts/implementer'
export { generateReviewerPrompt } from './prompts/reviewer'
export { parseArgs, type CommandName, type CommandContext } from './cli/commands'
export { getStatusRows, formatStatusTable, type TaskStatusRow } from './cli/status'
export { runDiagnostics, formatDiagnostics, type DiagnosticCheck } from './cli/doctor'
export { generateDefaultConfig, writeConfig } from './cli/init'
